/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 Arrow3.gltf 
*/

import React, {useEffect} from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export default function Model(props) {
  const group = React.useRef()
  const { nodes, materials, animations } = useGLTF('/Arrow3.gltf')
  const { actions } = useAnimations(animations, group)

  useEffect(() => {
    actions.default.play();
    })

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="blockbench_export">
        <group>
          <group name="cuboid" position={[0, 0, 0]}>
            <mesh name="cuboid_1" geometry={nodes.cuboid_1.geometry} material={nodes.cuboid_1.material} position={[0, 0, 0]} rotation={[0, 0, -Math.PI]} scale={window.innerWidth/600 + 3}/>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/Arrow3.gltf')
